### ISSUE TITLE
Automated Release

### ISSUE THREAD

**Issue by ladeak** [ohanlon/Goldlight.HttpClientTestSupport#4]
- would you mind creating a new nuget pkg for the above library?
- would you prefer me to setup simple github actions for the repo? (so then you can setup nuget secrets, and it could auto-push on release)

**Comment by ohanlon** [comment]
I've pushed the latest version to Nuget; the Actions option is one I've got in my backlog of things to do.

**Comment by ladeak** [comment]
Thank you.
